version: '2'
services:
     
  maven-app-build:
     user: "997:994"
     image: rcx-java-build:latest
     volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "${JENKINS_HOME}:${JENKINS_HOME}:rw"
      - "${WORKSPACE}:${WORKSPACE}:rw"
